### ISSUE TITLE
[BUG] opening app

### ISSUE THREAD

**Issue by piera97** [rivafarabi/deckboard#1008]
When i try to open the app i see a message of an error "the device can't connect to your computer"
i bought the pro version for the mobile version, but still the same error appears

Screenshots
[https://cdn.discordapp.com/attachments/839933106156994610/1144684245999165490/Screenshot_20230825_192603.jpg](url)

Server App 
 - OS: Windows
 - Version 2.1.4

Client App 
 - OS: Android 13
 - Version 2.1.1
![Screenshot_20230825_192603](https://github.com/rivafarabi/deckboard/assets/143213458/3e8bf0b3-3f82-4ecb-8d5b-d3c012821c49)

**Comment by rivafarabi** [comment]
Can you provide these two files?
- database.db (located in C:\Users%USER%\deckboard)
- log.log (located in located in C:\Users%USER%\AppData\Roaming\Deckboard)

And also, can you access `https://[YOUR_PC_IP_ADDRESS]:8500` from your device? The server works properly if it says
> Cannot GET /

Otherwise, check your firewall as mentioned in [this page](https://github.com/rivafarabi/deckboard/wiki/Troubleshoot)

**Comment by piera97** [comment]
Perfect I solved the problem, thank you very much!
Now it works perfectly!

Il giorno ven 25 ago 2023 alle ore 21:23 Riva Farabi <
***@***.***> ha scritto:
