### ISSUE TITLE
[BUG] Quit button doesn't work on MacOs

### ISSUE THREAD

**Issue by linqueta** [rivafarabi/deckboard#1012]
**Describe the bug**
When using it on MacOs (the version 2.1.4), Deckboard app only gets closed if you go to Activity Manager and force it to quit, so, the Quit button isn't working properly.

When calling to shut down the computer, MacOs isn't closing the app either and gets stuck.

**To Reproduce**
1. Open Deckboard on MacOs
2. Click to Quit

**Expected behavior**
The app isn't finished but it should be.

**Screenshots**

https://github.com/rivafarabi/deckboard/assets/21321082/94db181f-3e2d-4d48-aa2a-e7be69699be9

**Server App (please complete the following information):**
 - OS: MacOs Monterey 12.4
 - Version 2.1.4

**Client App (please complete the following information):**
 - OS: [e.g. Android 9]
 - Version [e.g. 1.9.60]

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**

**Comment by rivafarabi** [comment]
The current behavior, clicking the close button will close the app window but doesn't stop the server service entirely. In order to stop the server entirely, you can do this by doing that you does through Activity Manager, or right clicking the Deckboard app icon on the top menu bar and select Quit.

**Comment by linqueta** [comment]
Even clicking on the Deckboard Icon with right-click asking to Quit it's not finishing. 

I'm using a prompt to kill it before I click to restart or shutdown my MacBook using `killall Deckboard`

**Comment by jacix** [comment]
I'm having the same issue on MacOS Sonoma 14.1.2 with Deckboard 2.1.4.  The only way to kill the application is through the terminal (killall as @linqueta described, "_pkill Deckboard_", etc) or Force Quit in the Apple menu.  To fix that I've created a Deckboard button to kill itself.  (Grim, I know!). "Quit" in the Deckboard app menu icon or CMD-Q while Deckboard has focus will close the user-facing application, but the daemon keeps running and blocks shutdown. It also means having to kill it manually before being able to see the UI again. 

That said, I really like Deckboard and once this issue is fixed I'll happily buy the Pro version.

**Comment by rivafarabi** [comment]
The fix for unresponsive "Quit" button in MacOS dock menu is available in beta release of server app version [3.0.0-rc3](https://github.com/rivafarabi/deckboard/releases/tag/v3.0.0-rc3)

Feel free to open a new thread if the problem still persist.

**Comment by jacix** [comment]
Thank you @rivafarabi - 3.0.0-rc3 solves it for me on both of my Macs.  Nicely done!!
