### ISSUE TITLE
Deckboard 3.0.0-rc3: Boards not working

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1027]
I installed the new Deckboard 3.0.0-rc3 and testet the Advanced Boards.
But for me this seems not to work.
The 4 Boards are somewhere between my other boards.
If i add a board with sliders my Android device still shows Buttons but with a green "!" instead of a slider.

Maybe i also need a new app on my Phone?
I use the latest version from Google Play Store.

**Comment by rivafarabi** [comment]
Sorry my bad, I need to address this more accessible next time. 
All new features from version 3.0.0-rc3 is still in beta and only can be used by client app version >3.0.0, which also currently in beta.

I have mentioned it on Twitter, that you need to join beta program to download the latest open beta release from Google Play. Scroll down the app page on Google Play and you will find this section like picture below.
![image](https://github.com/rivafarabi/deckboard/assets/4427494/8fc701fb-b77e-4017-8586-4ebd90597e1b)

Just click Join. Let me know if you still have an issue getting this relesase.

**Comment by newteenpt** [comment]
Hello
I just joined the Beta program on Google Play, but it still downloads the old app version, which means I can't use the new Desktop slider features, I face the same issues as Schousda. I have the pro version bought, but the new beta version isn't available there either.

Can you help us out? I'd really love to try this out, otherwise I'll have to unfortunately switch to Touch Portal app, asap, because sliders are essential to me. Also, will the advance board really be limited to 4x3 icons on each tab? Or is it suppoded to merge all button sets in one tab? Otherwise that's very limited.

Thank you Riva :)

**Comment by rivafarabi** [comment]
Have you tried to force quit the Google Play service on your device and restart it afterward? Some managed to download the beta version by doing that.

As for the button grid size in the advance board section, I planned to have 6x6 grid size per section on the pro version, so one advance board can hold a max 12x12 grid in total. 
The basic version however is limited to 4x3 per section + additional adwall.

**Comment by schousda** [comment]
Thank you for the advice about the Beta program.
It looks like it needs some time until Google Play delivers you the Beta app.
Just wait for a while and try to update again.
You also need to join the Beta program for Deckboard Pro to get all functions.

**Comment by rivafarabi** [comment]
6x6 grid size for advance board's button grid section is included in [v3.0.0-rc4](https://github.com/rivafarabi/deckboard/releases/tag/v3.0.0-rc4)

**Comment by newteenpt** [comment]
Hello Riva
Thank you very much for the amazing work you're doing. I'll try the CR4 version next week.

I was able to use the CR3 version and there are a few fixes I'd suggest, if you think they make sense and are possible:
- Possibility to optionally show all 4 canvas at the same time (very useful for tablets)
- Possibility to remove the canvas background rectangles
- Possibility to adjust paddings/margins for each of the 4 canvas (so it is possible to make the 4 canvas look like they're merged, just like in a simple board)
- Possibility to have the same PC volume slider template as the one for OBS volume, the wheel isn't always convenient
- Possibility to show the volume sliders in vertical, instead of horizonta

At the moment, these are the main fixes I believe will be a game changer. If I have more feedback, I'll tell you next week.
Thank you very much
Best regards

**Comment by rivafarabi** [comment]
Closing this due to deprecation of Advance Board in future beta release. Reference: [X](https://twitter.com/rivafarabi/status/1783177091426681229)
