### ISSUE TITLE
No automatic updates and no update button on the app

### ISSUE THREAD

**Issue by ObiwanKenoob** [rivafarabi/deckboard#118]
So, I've been seeing infos about updates and all and my desktop app is stuck on 1.2.641 untill now.

I'm hesitant on downloading a new version, and losing the pannels I have working for now.

Please let me know if there's something I can do go get the updated versions. Also a button on the settings menu that forcely checks for updates would be nice :)

**Comment by rivafarabi** [comment]
You can actually download and install the newer version of Deckboard without losing your existing buttons, because all saved settings and boards separated from the app folder. 

If you still hesitate to update, you can backup database.db file located in C:/Users/%USERNAME%/deckboard

And thanks for the advise :)
