### ISSUE TITLE
Question and spotify

### ISSUE THREAD

**Issue by LukysGaming** [rivafarabi/deckboard#290]
Hi can you made version working with streamelements?
Make support discord?,its better :)
Spotify controls <pause,next...> doesnt work.

**Comment by LukysGaming** [comment]
https://prnt.sc/pn68mx  https://prnt.sc/pn68v2

when openin' obs

**Comment by derMiepz** [comment]
StreamElements doesn't have it's own version of OBS. OBS.Live is a plugin for OBS Studio. 
And your OBS problem is not related to Deckboard. I'd recommend you to ask in the official OBS Discord [discord.gg/obsproject](url) for help.

**Comment by Yurlyn** [comment]
To control Spotify you will need to login here:
![image](https://user-images.githubusercontent.com/42919979/67636497-94cfa400-f8d1-11e9-8972-2c3544c153f8.png)

And what exactly would you want to do with Discord? Mute the mic or other people? If so, you can set hotkeys in Discord itself and then set up a keyboard macro in Deckboard.
Step 1: In Discord click the icon marked by the arrow:
![image](https://user-images.githubusercontent.com/42919979/67636657-2b509500-f8d3-11e9-87bf-3eea3dc00108.png)
Step 2A: Click on "Keybinds";
Step 2B: Set your desired (and (globally) unique) macro keys for either or both these settings:
![image](https://user-images.githubusercontent.com/42919979/67636775-3f48c680-f8d4-11e9-974a-9276d76ab741.png)
Step 3A: In Deckboard, set the action to "Keyboard Macro" (which is the default);
Step 3B: Set your Keypress here;
Step 3C: If you have a keypress like mine, using two characters only, then click this keyboard icon to toggle it to an "A" icon. This will change it to grabbing all your subsequently pressed keys instead of a combination of supported keys pressed simultaneously. With my example I'll need to set it to the "A" icon;
Step 3D: Do NOT set this. Doing so will make Discord (or any program set here) move to the foreground before the keyboard macro is used. This will take the focus of your current program or game which can be horrible when playing games xD Also, if you have set this you'll have to delete the button and start back at step 3A.
![image](https://user-images.githubusercontent.com/42919979/67637370-61ddde00-f8da-11e9-84c8-14df637337c6.png)

When set correctly you can now toggle the mutes on both your mic and output of Discord. Hope this helped.

**Comment by LukysGaming** [comment]
The spotify doesnt work  [i am logged]

**Comment by rivafarabi** [comment]
Are you registered as spotify premium user? Spotify playback API can  only
be accessed by premium user only.

**Comment by LukysGaming** [comment]
ahhh k
