### ISSUE TITLE
Unable to connect to local network

### ISSUE THREAD

**Issue by Delirya** [rivafarabi/deckboard#312]
Hello. I've had connection issues for a month or so. I tried uninstalling/reinstalling and checking firewall exceptions before coming here. I did see some threads mention pointing the firewall exception to a directory under users, but I didn't find any executable there. I was really enjoying using this for streaming, and bought the app because it was so good!

Attached are my db, log and a screenshot. I did try to figure this out before posting as I didn't want to be a nuisance.

DB file is [here ](https://drive.google.com/open?id=1IEGwDJQTWk06y232Po-o_IZbO4zVhzss)

The log file: 
    [2019-11-20 02:00:46.533] [error] Something went wrong: Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

![Screen Shot 11-20-19 at 02 10 AM](https://user-images.githubusercontent.com/42555594/69217154-edded080-0b3b-11ea-9b0e-d9fb6d6d3e99.PNG)

**Comment by rivafarabi** [comment]
May I know which version are you running on both your PC and device? I have checked your DB file and works fine on version 1.8.1 (PC) and version 1.6.0 (phone)

**Comment by Delirya** [comment]
1.81 on PC, and 1.6.0 Build 1050 on Android. My phone is wanting to connect, but its the desktop app that wont let me. It just says "not connected to local network" or "not device connected." I'm assuming something went sideways after a windows update but I have no idea.

I went through this thread https://github.com/rivafarabi/deckboard/issues/240#issuecomment-527549456 first, but I didn't have any .exe at c:\users\(user)\appdata\local\programs\deckboard location to add to my firewall.

**Comment by rivafarabi** [comment]
You need to match the path of deckboard.exe in your own computer with the firewall's allowed app path setting. Best way to find the path is right click the app shortcut, then right click and select 'Open file location'.

**Comment by Delirya** [comment]
I checked that before posting, I only mentioned that alternative location because you did in that thread. I have it enabled on both private and public networks. 
![Screen Shot 11-21-19 at 04 19 PM](https://user-images.githubusercontent.com/42555594/69377663-c17d9e00-0c7a-11ea-9dec-e908673974a5.PNG)

**Comment by rivafarabi** [comment]
Okay I'm gonna check the log file. Can you send me the whole log.log file

**Comment by Delirya** [comment]
I think this is the right file?
https://docs.google.com/document/d/13B36noe2JrDiXJ4qDYSafqN_HhuER1o3uZiegf-ftM4/edit?usp=sharing

**Comment by rivafarabi** [comment]
I have checked the log, but it seems the said error doesn't effect the connection. 
And I did some review and find out the only potential reason why Deckboard doesn't list any IP address even though it is connected to the network is because it only listed IPv4 address with '192.168.xxx.xxx` pattern.

I suggest to open your command prompt, run ipconfig, then try the connection using IPv4 address listed from your device
![tempsnip](https://user-images.githubusercontent.com/4427494/69423203-10e5cc00-0d58-11ea-96cb-ac50bd6774e4.png)
.

**Comment by Delirya** [comment]
oh my goodness, I'm sorry to be such a bother. When I checked ipconfig, my ipv4 was set to 10.0.x.x. when I changed the range to 192.168.x.x everything started to work again. My apologies! Thank you so much for taking your time to help out, when it wasn't your glorious application! 👍

**Comment by rivafarabi** [comment]
Glad to hear it 😁

**Comment by Bearili** [comment]
Hi, I am having this same issue. Im not sure why I get "not connected to local network". I have tried wifi and LAN and have the same issue on both. I also cannot connect via usb. I tooks like something worked for Delirya above but I dont understand what made it work. I allowed my Windows Defender to let Deckboard through and didnt work. Not sure how to get Log files otherwise Id add those here. Let me know if anyone if free to help. thanks

**Comment by Bearili** [comment]
I should also add that I do not get an error. I try clicking "refresh" but the window just closed after that. No error windows. It almost feels like the whole application is dead, though it connects to OBS and im able to connect my spotify account ect. ... Ive tried unistalling and reinstalling aswell

**Comment by Bearili** [comment]
Currently using 1.9.2 on desktop(windows 10). and 1.9.2 pro on android (galaxy s10 plus)
