### ISSUE TITLE
[REQUEST] Remove Hamburger Menu from Android app

### ISSUE THREAD

**Issue by Reinforcementshavearrived** [rivafarabi/deckboard#398]
As the title suggests I think there should be an option to remove the hamburger menu from the Android App as it puts itself in front of other buttons i set up correctly in many configurations. I know there's a menu on the left but I barely use it as I set a simple folder structure to navigate.

The software is great, please keep it up.

**Comment by machineabuse** [comment]
I would suggest that the hamburger menu be accessible through swiping in from the side replacing the swipe through screens behavior.

The current behavior with being able to swipe through screens sometimes triggers when intending to make a quick/successive button press(es). Also because the order of screens sometimes randomly assigns itself when launching the app, being able to swipe through screens is of limited utility if you have more than just a handful.

**Comment by poisonbl** [comment]
At least in version 1.9.5 on android, there's a setting "Show menu floating button" that toggles that button and works quite well.

**Comment by machineabuse** [comment]
@poisonbl good catch! It's a really nice look now!

**Comment by Reinforcementshavearrived** [comment]
I didn't know that. Thank you a lot.
