### ISSUE TITLE
[Feature Request] Send hotkey to specific Application

### ISSUE THREAD

**Issue by Koxicain** [rivafarabi/deckboard#420]
It would be awesome if it would be possible for Deckboard to send a hotkey to a Specific Application.
Forinstance Discord only or OBS only incase you have the same hotkey in 2 programs. Or want to avoid it triggering something ingame. 

For my usecase i have 2 OBS windows open and i would like to make a macro that mutes 1 OBS mic while Opening the other and other way around. This is a very unique case but it could benifit others.

Fx. A lot of games uses Modifiers + F(x) keys these are also common macro/hotkeys to use in the software. If Deckboard would be able to only send the Hotkey to a specific program that would be awesome. I hope it isnt too difficult but i know its possible :D

**Comment by digitalfiz** [comment]
I think that's what the 'Run on' functionality is for but it seems to be broke in my testing and others have submitted this but #59

**Comment by Yurlyn** [comment]
AutoHotkey can send specific hotkeys to specific windows. Maybe that helps.

**Comment by Koxicain** [comment]
> AutoHotkey can send specific hotkeys to specific windows. Maybe that helps.
Im trying to simplify my setup, not making more scripts :)

**Comment by Yurlyn** [comment]
Do you have the OBS'es run from different folders? If so, then maybe starting a specific OBS could work as a call to open that specific OBS. That would however not minimize or close the previous OBS but that could be fixed with multi-actions and a hotkey that presses alt+space followed by the corresponding action (m = maximize, n = minimize, r = restore and c = close on English Windows configurations).
