### ISSUE TITLE
Unable to select scenes since Streamlabs update

### ISSUE THREAD

**Issue by TheArdeck** [rivafarabi/deckboard#429]
Ever since there was a streamlabs update a few days ago, my scene buttons have stopped functioning. Checking deckboard pro, all scenes have changed to empty with "No data available" from the scene select drop down. I've rebooted and closed down both applications as well as running both as administrator.

The app says it connects successfully to streamlabs on the port specified and every other button works, except the scene select function.

I've checked through the issues tab and cant find a similar issue post, so I might be the only one. (It was 3am so I might have missed something when I checked).

I've recently downloaded the app from the app store, so I'm not sure if this is usual until a deckboard update/patch is released or if this is something new.

**Comment by rbrito89** [comment]
I'm also having this issue. Streamlabs OBS is running and Deckboard shows its connected on the specific port. All other buttons are working for local applications (such as launching Steam, Discord, etc). The issue seems to be specific to Streamlabs OBS and controlling sources, scenes, and audio. I've tried reinstalling Deckboard on Windows and Deckboard PRO on Android; no changes. :(

![1](https://user-images.githubusercontent.com/1112571/83359030-7e953500-a345-11ea-97b0-997c3b15164c.jpg)
![2](https://user-images.githubusercontent.com/1112571/83359031-7e953500-a345-11ea-9c66-b06e9655cea7.jpg)

**Comment by rivafarabi** [comment]
May I know which version of Deckboard (server) and Streamlabs OBS are using?

**Comment by TheArdeck** [comment]
Thanks for getting back to us, Deckboard server is on 1.9.31 and streamlabs obs version says 0.22.0. :)

**Comment by rbrito89** [comment]
My versions are the same as @TheArdeck

**Comment by MauroFelicio** [comment]
hi, i have the same problem, i'm desperate i can't change the programmed scenes and effects. Beckboard 1.9.41-rc4 and Streamlabs OBS 0.22.0.

**Comment by harfmil** [comment]
I am also experiencing this issue. Deckboard 1.9.31 and Streamlabs 0.22.1

**Comment by rivafarabi** [comment]
The fix is available in version [1.9.41-rc5](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.41-rc5).

Let me know if the bug still exists.

**Comment by TheArdeck** [comment]
Hi,

Unfortunately, I'm unable to test. Streamlabs has updated again to 0.22.1.
This hasnt fixed the issue for Streamlabs 0.22.1 but someone else might be
able to confirm a 0.22.0 fix.

Thanks

**Comment by rivafarabi** [comment]
The fix for Streamlabs OBS 0.22.1+ is available in version [1.9.41-rc6](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.41-rc6)

Streamlabs OBS 0.22.1 requires API token to fetch scenes and other items

API token can be found in Settings>Developer menu
![image](https://user-images.githubusercontent.com/4427494/83621414-d687a200-a5b8-11ea-9443-b06e0a7596e1.png)

copy the token to API token field in Deckboard Streamlabs OBS setting menu
![image](https://user-images.githubusercontent.com/4427494/83621576-09319a80-a5b9-11ea-9017-1fc4847714f9.png)

**Comment by TheArdeck** [comment]
Ahh yeah, all working now! Thanks for your help! Much appreciated.

**Comment by rbrito89** [comment]
Wait, I'm a little lost. How do you enable the Developer options in settings? I do not have that option. I had to get the API key from the SLOBS dashboard website.
![1](https://user-images.githubusercontent.com/1112571/83629999-158e0700-a569-11ea-88f3-9447fa439074.jpg)
![2](https://user-images.githubusercontent.com/1112571/83630000-16269d80-a569-11ea-999d-c4710722eb91.jpg)
![3](https://user-images.githubusercontent.com/1112571/83630002-16269d80-a569-11ea-8507-b51f040170c1.jpg)

**Comment by TheArdeck** [comment]
Under Streamlabs settings, click on "Remote Control" then click on the blurred QR code you're presented with. Underneath there is the "Show Details" directly underneath the image. When you click it, you get your API token and your address. :)

**Comment by rbrito89** [comment]
@TheArdeck Thank you very much, that worked!

**Comment by harfmil** [comment]
Confirmed fixed! Thank you for the quick response!
