### ISSUE TITLE
Suggestion for new feature

### ISSUE THREAD

**Issue by ObiwanKenoob** [rivafarabi/deckboard#46]
This would be awesome!

As a streaming tool, this app can have so many functionalities.

Something I'd like to see in the future is this.. "Macro the macros"

As for example:

I create a macro for selecting an specific scene and playing a sound file..

I'd like to have the option to reference those macros, and then, creating a sequence to one button, like switching to the desired scene and playing a music, for a certain time, and then going back to the original scene.

If that's possible this app can easily overthrow any streamdeck..

**Comment by AngelicDivine** [comment]
This is really not a bad idea. i would not mind seeing this in the future. I would say that this would be pushed back a ways because of the app being in a very beta state. 

I was told that stuff like this and also using the deckboard to work in programs like davinci resolve would have to wait because, this team is really working hard to fix the bugs for the client, the app and also better functions with OBS and streamlabs obs.

**Comment by rivafarabi** [comment]
So like a sequence timeline then. It's great idea, but not the near future release. Just as @AngelicDivine said, the app need improvements for its basic functions.
