### ISSUE TITLE
Can't Control Spotify even after buying the PRO app

### ISSUE THREAD

**Issue by thelonescaper** [rivafarabi/deckboard#483]
I have tried re installing, clearing all data from computer. from the app data folder and all. but still I'm **unable to use the spotify control feature on my app**. also for key shortcuts the **"Run On"** option doesn't work too.
please help

**Comment by rivafarabi** [comment]
Is your Spotify account a premium one (with subscription)?

**Comment by thelonescaper** [comment]
No, it's a free account..

**Comment by rivafarabi** [comment]
Based on Spotify API documentation, playback control is available for Premium user only.

This matter is also stated on the website and this github readme page

**Comment by thelonescaper** [comment]
Okey I'll buy the premium version.

But what about the Keyboard macro?
After setting up the keypress under that the "Run On" option doesn't work...

**Comment by rivafarabi** [comment]
"Run On" dropdown bug has been fixed in version [1.9.60-rc2](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.60-rc2).

Note: all keyboard macro with specific app selected will be activated once the the app is opened. Once the macro button get pressed, it will focus the app window first before running keypress.
