### ISSUE TITLE
Bug when i open Obs with Deckboard.

### ISSUE THREAD

**Issue by Johan140911** [rivafarabi/deckboard#484]
I have a problem when I try to start Obs, it give the error: Failed to find locale/en-US.ini and Failed to load locale.
Pls can help me?
![Error 08_14_2020 6_55_54 p  m](https://user-images.githubusercontent.com/65095603/90300454-1d6b0100-de60-11ea-8b65-72e884531d01.png)
![Error 08_14_2020 6_56_01 p  m](https://user-images.githubusercontent.com/65095603/90300461-278cff80-de60-11ea-90cb-578a02aec8ab.png)

**Comment by rivafarabi** [comment]
Sorry for the late reply.
It seems the error is intended because OBS Studio need to be running from the working directory (`C:\program files\obs-studio\bin\64bit`).

So, the other way around to run this program is create this batch script
`cd C:\Program Files\obs-studio\bin\64bit && start "OBS Studio" "C:\program files\obs-studio\bin\64bit\obs64.exe"`
