### ISSUE TITLE
Deckboard doesnt connect with new update 1.2.62

### ISSUE THREAD

**Issue by alienize13** [rivafarabi/deckboard#53]
It worked great for a week, had buttons programmed and they worked but after updating to 1.2.62 on my PC my Phone and Tablet now no longer connect to the PC.  I Uninstalled and reinstalled on both platforms but it still wont connect.  I went back to 1.2.61 on the PC and still it will not connect.  I checked my Firewall and it is set to allow all traffic from Deckboard.  Any thing else I can try?

**Comment by alienize13** [comment]
I only have one network so only 1 IP to pick from, I even changed it to a static IP and it still no longer sees the connection.

**Comment by rivafarabi** [comment]
Can you post the log file located on %USER%/AppData/Roaming/Deckboard/log.log?

**Comment by EntityMike** [comment]
Hello! I just found this app today. Downloaded and configured it today on my Windows machine using proper authenication on my web socket, etc. However, I'm having the same issue - I got my Deckboard application on Windows working fine and interacting with my OBS Studio. However, when I try to connect from my Android app to to my Windows app it gives error. I only have 1 IP address as well under "possible IP addresses". Attached is my log.log under the path you specified. When I try reconnecting (with same error), no new timestamped logs appear.

Let me know if there's anything else I can provide, because I would love to get this running! :)

[log.log](https://github.com/rivafarabi/deckboard/files/2618434/log.log)

**Comment by rivafarabi** [comment]
Which error did you encounter? Is it the windows app that gave you error or the android app? If windows app the one that gave you an error, post the screenshot here.

**Comment by EntityMike** [comment]
On Android when connecting to Windows IP is where the error occurs. "Uh Oh! : The device can't connect to your computer. Please try again."

**Comment by rivafarabi** [comment]
While I'm still solving the issue, please check the following settings:

- Allow connection in Firewall setting
- Turn off VPN on both sides
- Make sure both device connect to the same network.
- Turn off your mobile data connection on your phone

**Comment by EntityMike** [comment]
Will try and update this comment as I go. Thanks!

**Comment by EntityMike** [comment]
Looks like my issue is solved. Thanks for your quick response. I'm not sure about the initial thread though.

**Comment by rivafarabi** [comment]
Nice, enjoy the app!
