### ISSUE TITLE
Vibration Feedback and secured connection on Deckboard pro

### ISSUE THREAD

**Issue by son12710** [rivafarabi/deckboard#72]
Hi, 

I've just purchased Deckboard Pro and it's pretty sweet. however, I have a few question 
1) Is it possible to add vibration feed back to the Free/Pro version?
2) Is the app connect to the pc using secured connection? Is it safe to use in public network? I want to use "type Text" feature but i dont know if the text is encrypted

**Comment by rivafarabi** [comment]
1. Haptic feedback should have already been added since version 1.2.5.
2. Currently, no. No authentication or something like that. Just simple
websocket connection. I advice you to use it on your own wireless network.
3. The android app doesn't store the command value (text, url, folder name,
etc). All those values are kept on your computer only.

**Comment by son12710** [comment]
thanks for getting back so early.
1) my bad, i accidentally disabled haptic feedback globally on my phone, all good
2) thanks, I'll use on my home network for now. After browsing for a bit, looks like there are already some requests for bluetooth and USB mode. Looking forward to it
