### ISSUE TITLE
Gifs on Buttons

### ISSUE THREAD

**Issue by ObiwanKenoob** [rivafarabi/deckboard#73]
Since we can add images for the buttons, i figured I could add some stuff to make it easier just to glance at the button, without the need to read them.

I had some sources on OBS that were gifs, and I added the same gifs on deckboard for each respective button, so i can switch between each gif easily.

Problem is, that the android app, cannot handle more the 3 gifs at once. If I have 3 gifs loaded it works fine, but if I add another one, either the app shut down on my phone, or it says it had problems while reloading.

If you could add a better support for gifs on the mobile side of the app, it would be great!

**Comment by rivafarabi** [comment]
Thanks for the info.

Have you consider the size of GIF file used on the app? Because running GIF took some process and memory, I advise you to compress the the gif files. I recommend this site [https://ezgif.com](url).

Yes, I tried using 8 gif files, and crashed after switching boards back and forth. Turns out the total size of the gifs is too large too handle (more than 10mb). After the compression I tried using 8 gifs at the same time and it run fine (around 100 to 200 kb each)
[https://drive.google.com/file/d/1OBSEdeH3qdIxaGdAHTa794wIX2QZtOM4/view](url)
